---
- name: Setup Webserver
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

- name: Setup Dbserver
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install MySQL
      yum:
        name: mariadb-server
        state: present
    - name: start and enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
